### PR TITLE
React client

### PR DESCRIPTION
**Pull request by izaakf**
As @CianLR and @AlexKraak noted in #6 react.js is a more appropriate framework to use for this project due to scaling reasons.

@sentriz and I have been discussing whether we should use Vue or React here. I believe React is the more appropriate choice, but please do follow up with @sentriz before merging as this is a decision that will ultimately impact the organisation as a whole.

### CODE REVIEW

**Comment by sentriz** [comment]
sammy my good friend. i think this is the greatest pr in the entire universe!!!! L G T M!!!!!!!!!!!!!!!!!!!!!

**Comment by sentriz** [comment]
here is a working copy of the compiled site: https://home.senan.xyz/helo/

**Comment by izaakf** [comment]
@sentriz thank you very much for creating a live demo!

Although it would be greatly appreciated if you could put some authentication in front of this. The website contains business confidential information, and exposing this to the open internet could potentially have dangerous effects on company stock prices. If you are currently unable to provide an authentication portal for organisation members, please consider pointing to a development backend in order to preserve customers data!

**Comment by sentriz** [comment]
@izaakf sammy my friend, your wish is my command! helo client is now using the dev api!
thank you kindy, Senan

**Comment by izaakf** [comment]
@sentriz Brilliant sammy! :shipit:

**Comment by AlexKraak** [comment]
Please add this to the docker file for ease of deployment

**Comment by sentriz** [comment]
@AlexKraak brilliant! I've created a patch on @izaakf's fork.

**Comment by izaakf** [comment]
@sentriz @AlexKraak @izaakf brilliant! lgtm

**Comment by AlexKraak** [comment]
:ship: :ship: :gem: :rocket: :rocket:

**Pull request merged**
