### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by CianLR**

### CODE REVIEW

**Comment by AlexKraak** [comment]
sorry, this is too political

**Comment by sentriz** [comment]
my team need this for Q3, when we will require help from a sister team (who are new to the project!)

**Comment by izaakf** [comment]
Don't merge fast!

**Comment by iandioch** [comment]
We shouldn't merge fast, Mr Freeman is right. But it is vital that we should fail fast! My previous team's sister team in Dubai's support team's engineering-productivity team's parent team's tooling team made this mistake before.

**Comment by AlexKraak** [comment]
Yeah this needs tests please

**Comment by izaakf** [comment]
helo @CianLR please see #4. as @AlexKraak has stated this project uses troff. Please consider changing the markdown file to be project compliant.

Thanks on behalf of the helo team in Serbia.

**Comment by CianLR** [comment]
Hello I have added the compatibility PTAL

**Comment by izaakf** [comment]
helo @CianLR,

I am glad to see that you've fixed our CoC! Looking forward to seeing this in action :)

Great work,
Zak

**Comment by AlexKraak** [comment]
:sagittarius:

**Pull request merged**
